export const priceBands = [
  {
    name: "Digital Presence Check",
    slug: "digital-presence-check",
    price: "KES 15,000",
    numericPrice: 15000,
    range: "Small package",
    summary: "A focused review of your website, search presence, social proof, customer journey, and inquiry path.",
    bestFor: "Budget-conscious founders who need to know what is wrong before spending more.",
    includes: ["Website/search/social review", "Homepage clarity check", "Inquiry path review", "SEO basics check", "Short action report"],
  },
  {
    name: "Website Refresh Audit",
    slug: "website-refresh-audit",
    price: "KES 25,000",
    numericPrice: 25000,
    range: "Small package",
    summary: "A deeper audit for existing websites that need a serious fix plan before redesign or marketing.",
    bestFor: "Businesses with a site that looks outdated, unclear, slow, or weak on inquiries.",
    includes: ["Full website audit", "SEO and content review", "Trust/proof review", "Mobile review", "Prioritized fix plan"],
  },
  {
    name: "Client Magnet Starter Page",
    slug: "client-magnet-starter-page",
    price: "From KES 45,000",
    numericPrice: 45000,
    range: "Starter build",
    summary: "One polished page built to explain your offer clearly and guide visitors to WhatsApp, email, booking, or a form.",
    bestFor: "Lean founders, campaigns, launches, and service offers that need one strong action path.",
    includes: ["1-page website or landing page", "Responsive design", "Copy cleanup", "WhatsApp/email CTA", "Contact form", "Basic SEO", "Analytics setup", "Launch support"],
  },
  {
    name: "Business Website Refresh",
    slug: "business-website-refresh",
    price: "From KES 85,000",
    numericPrice: 85000,
    range: "Refresh build",
    summary: "A sharper version of your current website with stronger structure, copy, design, SEO foundations, and inquiry paths.",
    bestFor: "Growing SMEs with real proof and an existing presence that no longer reflects the business.",
    includes: ["4-7 page refresh", "Homepage/service/contact pages", "Copy restructuring", "Responsive design", "Image optimization", "Basic schema", "SEO metadata", "Analytics"],
  },
  {
    name: "Full Business Website",
    slug: "full-business-website",
    price: "From KES 120,000",
    numericPrice: 120000,
    range: "Full website",
    summary: "A complete multi-page business website with service pages, inquiry paths, social links, email capture, SEO setup, and launch support.",
    bestFor: "Serious SMEs that need a proper business website, not only a digital brochure.",
    includes: ["5-10 pages", "Content structure", "Custom design direction", "Service pages", "Contact/inquiry paths", "Social media integration", "Email capture", "SEO foundations", "Schema", "Analytics"],
  },
  {
    name: "E-commerce / Product Catalogue",
    slug: "e-commerce-product-catalogue",
    price: "From KES 150,000",
    numericPrice: 150000,
    range: "Product build",
    summary: "Product or catalogue websites with product structure, quote or checkout flow, payment support where scoped, and SEO foundations.",
    bestFor: "Product-based businesses that need catalogue, quote, checkout, or M-Pesa/payment support.",
    includes: ["Product/catalogue structure", "Product pages", "Quote or cart flow", "Payment/M-Pesa support where scoped", "Customer inquiry path", "Analytics", "SEO foundations"],
  },
  {
    name: "Full Client Magnet Website",
    slug: "full-client-magnet-website",
    price: "From KES 180,000",
    numericPrice: 180000,
    range: "Strategic website",
    summary: "Strategy, copy direction, custom page structure, proof sections, SEO foundations, email marketing readiness, and conversion flow.",
    bestFor: "Businesses that need the website to actively support trust, inquiries, and growth.",
    includes: ["Strategy and copy direction", "7-12 pages", "Service/pricing/proof pages", "Social media integration", "Lead capture", "Email marketing readiness", "Advanced SEO foundations", "Schema", "Conversion flow"],
  },
  {
    name: "Website + Follow-Up System",
    slug: "website-follow-up-system",
    price: "From KES 250,000",
    numericPrice: 250000,
    range: "Connected system",
    summary: "A website connected to CRM/contact capture, WhatsApp flows, email marketing, booking, lead routing, and automation planning with Rotsi.",
    bestFor: "Teams that lose opportunities after the first inquiry or need follow-up built into the journey.",
    includes: ["Website plus CRM/contact capture", "WhatsApp flow", "Forms or booking", "Lead routing", "Email marketing setup where scoped", "Automation planning", "Reporting handoff"],
  },
];
